name: Python Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        black-options: true
